---

name: 'Dependency Review'

on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969
        with:  # TODO: change to 'egress-policy: block' after couple of runs
          egress-policy: audit
      - name: 'Checkout Repository'
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@f46c48ed6d4f1227fb2d9ea62bf6bcbed315589e
