---

name: Labels

on:
  push:
    branches:
      - develop
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read  # for actions/checkout to fetch code
      issues: write  # for crazy-max/ghaction-github-labeler to create, rename, update and delete label
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@3de87da19416edc45c90cd89e7a4ea922a3aae5a
