---

name: Labels

on:
  push:
    branches:
      - develop
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read  # for actions/checkout to fetch code
      issues: write  # for crazy-max/ghaction-github-labeler to create, rename, update and delete label
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@3de87da19416edc45c90cd89e7a4ea922a3aae5a
